import { useLyric } from "@/lib/LyricContext";
import Head from "next/head";
import styles from "@/styles/Lyrics.module.css";

export default function Home() {
    const { socket, context, current, next, previous } = useLyric();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div
                    className={styles.lyrics}
                    style={{
                        //@ts-ignore
                        ["--image" as any]: `url(${context?.item.album.images[0].url})`,
                    }}
                >
                    <div>
                        <div className={styles.previous}>
                            {context?.lyrics && previous?.text}
                        </div>
                        <div className={styles.current}>
                            {context?.lyrics ? current?.text : "No Lyrics"}
                        </div>
                        <div className={styles.next}>
                            {context?.lyrics && next?.text}
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
